// College Basketball Teams organized by conference (2024-25 season)

export const basketballConferences = {
  SEC: [
    { name: "Alabama Crimson Tide", shortName: "Alabama", abbreviation: "ALA", primaryColor: "#9E1B32" },
    { name: "Arkansas Razorbacks", shortName: "Arkansas", abbreviation: "ARK", primaryColor: "#9D2235" },
    { name: "Auburn Tigers", shortName: "Auburn", abbreviation: "AUB", primaryColor: "#0C2340" },
    { name: "Florida Gators", shortName: "Florida", abbreviation: "FLA", primaryColor: "#0021A5" },
    { name: "Georgia Bulldogs", shortName: "Georgia", abbreviation: "UGA", primaryColor: "#BA0C2F" },
    { name: "Kentucky Wildcats", shortName: "Kentucky", abbreviation: "UK", primaryColor: "#0033A0" },
    { name: "LSU Tigers", shortName: "LSU", abbreviation: "LSU", primaryColor: "#461D7C" },
    { name: "Mississippi State Bulldogs", shortName: "Miss State", abbreviation: "MSST", primaryColor: "#660000" },
    { name: "Missouri Tigers", shortName: "Missouri", abbreviation: "MIZ", primaryColor: "#F1B82D" },
    { name: "Oklahoma Sooners", shortName: "Oklahoma", abbreviation: "OU", primaryColor: "#841617" },
    { name: "Ole Miss Rebels", shortName: "Ole Miss", abbreviation: "MISS", primaryColor: "#CE1126" },
    { name: "South Carolina Gamecocks", shortName: "South Carolina", abbreviation: "SC", primaryColor: "#73000A" },
    { name: "Tennessee Volunteers", shortName: "Tennessee", abbreviation: "TENN", primaryColor: "#FF8200" },
    { name: "Texas Longhorns", shortName: "Texas", abbreviation: "TEX", primaryColor: "#BF5700" },
    { name: "Texas A&M Aggies", shortName: "Texas A&M", abbreviation: "TAMU", primaryColor: "#500000" },
    { name: "Vanderbilt Commodores", shortName: "Vanderbilt", abbreviation: "VAN", primaryColor: "#866D4B" },
  ],
  "Big Ten": [
    { name: "Illinois Fighting Illini", shortName: "Illinois", abbreviation: "ILL", primaryColor: "#E84A27" },
    { name: "Indiana Hoosiers", shortName: "Indiana", abbreviation: "IND", primaryColor: "#990000" },
    { name: "Iowa Hawkeyes", shortName: "Iowa", abbreviation: "IOWA", primaryColor: "#FFCD00" },
    { name: "Maryland Terrapins", shortName: "Maryland", abbreviation: "MD", primaryColor: "#E03A3E" },
    { name: "Michigan Wolverines", shortName: "Michigan", abbreviation: "MICH", primaryColor: "#00274C" },
    { name: "Michigan State Spartans", shortName: "Michigan St", abbreviation: "MSU", primaryColor: "#18453B" },
    { name: "Minnesota Golden Gophers", shortName: "Minnesota", abbreviation: "MINN", primaryColor: "#7A0019" },
    { name: "Nebraska Cornhuskers", shortName: "Nebraska", abbreviation: "NEB", primaryColor: "#E41C38" },
    { name: "Northwestern Wildcats", shortName: "Northwestern", abbreviation: "NW", primaryColor: "#4E2A84" },
    { name: "Ohio State Buckeyes", shortName: "Ohio State", abbreviation: "OSU", primaryColor: "#BB0000" },
    { name: "Oregon Ducks", shortName: "Oregon", abbreviation: "ORE", primaryColor: "#154733" },
    { name: "Penn State Nittany Lions", shortName: "Penn State", abbreviation: "PSU", primaryColor: "#041E42" },
    { name: "Purdue Boilermakers", shortName: "Purdue", abbreviation: "PUR", primaryColor: "#CEB888" },
    { name: "Rutgers Scarlet Knights", shortName: "Rutgers", abbreviation: "RUT", primaryColor: "#CC0033" },
    { name: "UCLA Bruins", shortName: "UCLA", abbreviation: "UCLA", primaryColor: "#2D68C4" },
    { name: "USC Trojans", shortName: "USC", abbreviation: "USC", primaryColor: "#990000" },
    { name: "Washington Huskies", shortName: "Washington", abbreviation: "WASH", primaryColor: "#4B2E83" },
    { name: "Wisconsin Badgers", shortName: "Wisconsin", abbreviation: "WIS", primaryColor: "#C5050C" },
  ],
  "Big 12": [
    { name: "Arizona Wildcats", shortName: "Arizona", abbreviation: "ARIZ", primaryColor: "#CC0033" },
    { name: "Arizona State Sun Devils", shortName: "Arizona St", abbreviation: "ASU", primaryColor: "#8C1D40" },
    { name: "Baylor Bears", shortName: "Baylor", abbreviation: "BAY", primaryColor: "#154734" },
    { name: "BYU Cougars", shortName: "BYU", abbreviation: "BYU", primaryColor: "#002E5D" },
    { name: "Cincinnati Bearcats", shortName: "Cincinnati", abbreviation: "CIN", primaryColor: "#E00122" },
    { name: "Colorado Buffaloes", shortName: "Colorado", abbreviation: "COLO", primaryColor: "#CFB87C" },
    { name: "Houston Cougars", shortName: "Houston", abbreviation: "HOU", primaryColor: "#C8102E" },
    { name: "Iowa State Cyclones", shortName: "Iowa State", abbreviation: "ISU", primaryColor: "#C8102E" },
    { name: "Kansas Jayhawks", shortName: "Kansas", abbreviation: "KU", primaryColor: "#0051BA" },
    { name: "Kansas State Wildcats", shortName: "Kansas St", abbreviation: "KSU", primaryColor: "#512888" },
    { name: "Oklahoma State Cowboys", shortName: "Oklahoma St", abbreviation: "OKST", primaryColor: "#FF7300" },
    { name: "TCU Horned Frogs", shortName: "TCU", abbreviation: "TCU", primaryColor: "#4D1979" },
    { name: "Texas Tech Red Raiders", shortName: "Texas Tech", abbreviation: "TTU", primaryColor: "#CC0000" },
    { name: "UCF Knights", shortName: "UCF", abbreviation: "UCF", primaryColor: "#BA9B37" },
    { name: "Utah Utes", shortName: "Utah", abbreviation: "UTAH", primaryColor: "#CC0000" },
    { name: "West Virginia Mountaineers", shortName: "West Virginia", abbreviation: "WVU", primaryColor: "#002855" },
  ],
  ACC: [
    { name: "Boston College Eagles", shortName: "Boston College", abbreviation: "BC", primaryColor: "#98002E" },
    { name: "California Golden Bears", shortName: "California", abbreviation: "CAL", primaryColor: "#003262" },
    { name: "Clemson Tigers", shortName: "Clemson", abbreviation: "CLEM", primaryColor: "#F56600" },
    { name: "Duke Blue Devils", shortName: "Duke", abbreviation: "DUKE", primaryColor: "#003087" },
    { name: "Florida State Seminoles", shortName: "Florida St", abbreviation: "FSU", primaryColor: "#782F40" },
    { name: "Georgia Tech Yellow Jackets", shortName: "Georgia Tech", abbreviation: "GT", primaryColor: "#B3A369" },
    { name: "Louisville Cardinals", shortName: "Louisville", abbreviation: "LOU", primaryColor: "#AD0000" },
    { name: "Miami Hurricanes", shortName: "Miami", abbreviation: "MIA", primaryColor: "#F47321" },
    { name: "NC State Wolfpack", shortName: "NC State", abbreviation: "NCST", primaryColor: "#CC0000" },
    { name: "North Carolina Tar Heels", shortName: "North Carolina", abbreviation: "UNC", primaryColor: "#7BAFD4" },
    { name: "Notre Dame Fighting Irish", shortName: "Notre Dame", abbreviation: "ND", primaryColor: "#0C2340" },
    { name: "Pittsburgh Panthers", shortName: "Pittsburgh", abbreviation: "PITT", primaryColor: "#003594" },
    { name: "SMU Mustangs", shortName: "SMU", abbreviation: "SMU", primaryColor: "#0033A0" },
    { name: "Stanford Cardinal", shortName: "Stanford", abbreviation: "STAN", primaryColor: "#8C1515" },
    { name: "Syracuse Orange", shortName: "Syracuse", abbreviation: "SYR", primaryColor: "#F76900" },
    { name: "Virginia Cavaliers", shortName: "Virginia", abbreviation: "UVA", primaryColor: "#232D4B" },
    { name: "Virginia Tech Hokies", shortName: "Virginia Tech", abbreviation: "VT", primaryColor: "#630031" },
    { name: "Wake Forest Demon Deacons", shortName: "Wake Forest", abbreviation: "WAKE", primaryColor: "#9E7E38" },
  ],
  "Big East": [
    { name: "Butler Bulldogs", shortName: "Butler", abbreviation: "BUT", primaryColor: "#13294B" },
    { name: "UConn Huskies", shortName: "UConn", abbreviation: "CONN", primaryColor: "#000E2F" },
    { name: "Creighton Bluejays", shortName: "Creighton", abbreviation: "CREI", primaryColor: "#005CA9" },
    { name: "DePaul Blue Demons", shortName: "DePaul", abbreviation: "DEP", primaryColor: "#005EB8" },
    { name: "Georgetown Hoyas", shortName: "Georgetown", abbreviation: "GTWN", primaryColor: "#041E42" },
    { name: "Marquette Golden Eagles", shortName: "Marquette", abbreviation: "MARQ", primaryColor: "#003366" },
    { name: "Providence Friars", shortName: "Providence", abbreviation: "PROV", primaryColor: "#000000" },
    { name: "St. John's Red Storm", shortName: "St. John's", abbreviation: "SJU", primaryColor: "#C8102E" },
    { name: "Seton Hall Pirates", shortName: "Seton Hall", abbreviation: "HALL", primaryColor: "#004488" },
    { name: "Villanova Wildcats", shortName: "Villanova", abbreviation: "NOVA", primaryColor: "#003366" },
    { name: "Xavier Musketeers", shortName: "Xavier", abbreviation: "XAV", primaryColor: "#0C2340" },
  ],
  "American": [
    { name: "Charlotte 49ers", shortName: "Charlotte", abbreviation: "CHAR", primaryColor: "#046A38" },
    { name: "East Carolina Pirates", shortName: "East Carolina", abbreviation: "ECU", primaryColor: "#592A8A" },
    { name: "Florida Atlantic Owls", shortName: "FAU", abbreviation: "FAU", primaryColor: "#003366" },
    { name: "Memphis Tigers", shortName: "Memphis", abbreviation: "MEM", primaryColor: "#003087" },
    { name: "North Texas Mean Green", shortName: "North Texas", abbreviation: "UNT", primaryColor: "#00853E" },
    { name: "Rice Owls", shortName: "Rice", abbreviation: "RICE", primaryColor: "#00205B" },
    { name: "South Florida Bulls", shortName: "South Florida", abbreviation: "USF", primaryColor: "#006747" },
    { name: "Temple Owls", shortName: "Temple", abbreviation: "TEM", primaryColor: "#9D2235" },
    { name: "Tulane Green Wave", shortName: "Tulane", abbreviation: "TULN", primaryColor: "#006747" },
    { name: "Tulsa Golden Hurricane", shortName: "Tulsa", abbreviation: "TLSA", primaryColor: "#002D62" },
    { name: "UAB Blazers", shortName: "UAB", abbreviation: "UAB", primaryColor: "#1E6B52" },
    { name: "UTSA Roadrunners", shortName: "UTSA", abbreviation: "UTSA", primaryColor: "#0C2340" },
    { name: "Wichita State Shockers", shortName: "Wichita St", abbreviation: "WICH", primaryColor: "#FFC82E" },
  ],
  "Mountain West": [
    { name: "Air Force Falcons", shortName: "Air Force", abbreviation: "AF", primaryColor: "#003087" },
    { name: "Boise State Broncos", shortName: "Boise State", abbreviation: "BSU", primaryColor: "#0033A0" },
    { name: "Colorado State Rams", shortName: "Colorado St", abbreviation: "CSU", primaryColor: "#1E4D2B" },
    { name: "Fresno State Bulldogs", shortName: "Fresno State", abbreviation: "FRES", primaryColor: "#DB0032" },
    { name: "Nevada Wolf Pack", shortName: "Nevada", abbreviation: "NEV", primaryColor: "#003366" },
    { name: "New Mexico Lobos", shortName: "New Mexico", abbreviation: "UNM", primaryColor: "#BA0C2F" },
    { name: "San Diego State Aztecs", shortName: "San Diego St", abbreviation: "SDSU", primaryColor: "#A6192E" },
    { name: "San Jose State Spartans", shortName: "San Jose St", abbreviation: "SJSU", primaryColor: "#0055A2" },
    { name: "UNLV Rebels", shortName: "UNLV", abbreviation: "UNLV", primaryColor: "#CF0A2C" },
    { name: "Utah State Aggies", shortName: "Utah State", abbreviation: "USU", primaryColor: "#0F2439" },
    { name: "Wyoming Cowboys", shortName: "Wyoming", abbreviation: "WYO", primaryColor: "#492F24" },
  ],
  "WCC": [
    { name: "BYU Cougars", shortName: "BYU", abbreviation: "BYU-WCC", primaryColor: "#002E5D" },
    { name: "Gonzaga Bulldogs", shortName: "Gonzaga", abbreviation: "GONZ", primaryColor: "#002967" },
    { name: "Loyola Marymount Lions", shortName: "LMU", abbreviation: "LMU", primaryColor: "#862633" },
    { name: "Pacific Tigers", shortName: "Pacific", abbreviation: "PAC", primaryColor: "#F47920" },
    { name: "Pepperdine Waves", shortName: "Pepperdine", abbreviation: "PEPP", primaryColor: "#00205B" },
    { name: "Portland Pilots", shortName: "Portland", abbreviation: "PORT", primaryColor: "#330066" },
    { name: "Saint Mary's Gaels", shortName: "Saint Mary's", abbreviation: "SMC", primaryColor: "#003DA5" },
    { name: "San Diego Toreros", shortName: "San Diego", abbreviation: "USD", primaryColor: "#002855" },
    { name: "San Francisco Dons", shortName: "San Francisco", abbreviation: "USF", primaryColor: "#00543C" },
    { name: "Santa Clara Broncos", shortName: "Santa Clara", abbreviation: "SCU", primaryColor: "#862633" },
  ],
  "MVC": [
    { name: "Belmont Bruins", shortName: "Belmont", abbreviation: "BEL", primaryColor: "#003366" },
    { name: "Bradley Braves", shortName: "Bradley", abbreviation: "BRAD", primaryColor: "#C41230" },
    { name: "Drake Bulldogs", shortName: "Drake", abbreviation: "DRKE", primaryColor: "#004477" },
    { name: "Evansville Purple Aces", shortName: "Evansville", abbreviation: "EVAN", primaryColor: "#663399" },
    { name: "Illinois State Redbirds", shortName: "Illinois St", abbreviation: "ILST", primaryColor: "#CE1126" },
    { name: "Indiana State Sycamores", shortName: "Indiana St", abbreviation: "INST", primaryColor: "#003087" },
    { name: "Missouri State Bears", shortName: "Missouri St", abbreviation: "MOST", primaryColor: "#5E0009" },
    { name: "Murray State Racers", shortName: "Murray State", abbreviation: "MURR", primaryColor: "#002144" },
    { name: "Northern Iowa Panthers", shortName: "Northern Iowa", abbreviation: "UNI", primaryColor: "#4B116F" },
    { name: "Southern Illinois Salukis", shortName: "Southern Ill", abbreviation: "SIU", primaryColor: "#720000" },
    { name: "UIC Flames", shortName: "UIC", abbreviation: "UIC", primaryColor: "#001E62" },
    { name: "Valparaiso Beacons", shortName: "Valparaiso", abbreviation: "VALP", primaryColor: "#613318" },
  ],
};

// Sample basketball games for Feb 2026 season
// Games before Feb 8, 2026 have scores (completed)
export const sampleBasketballGames = [
  // Completed games (with scores)
  // Saturday Feb 1
  { home: "DUKE", away: "WAKE", time: "2026-02-01T18:00:00Z", conference: "ACC", homeScore: 82, awayScore: 67 },
  { home: "KU", away: "OKST", time: "2026-02-01T16:00:00Z", conference: "Big 12", homeScore: 91, awayScore: 78 },
  { home: "UK", away: "FLA", time: "2026-02-01T20:00:00Z", conference: "SEC", homeScore: 74, awayScore: 69 },
  { home: "PUR", away: "IND", time: "2026-02-01T14:00:00Z", conference: "Big Ten", homeScore: 88, awayScore: 72 },
  { home: "GONZ", away: "PEPP", time: "2026-02-01T22:00:00Z", conference: "WCC", homeScore: 95, awayScore: 62 },
  // Tuesday Feb 4
  { home: "CONN", away: "BUT", time: "2026-02-04T19:00:00Z", conference: "Big East", homeScore: 79, awayScore: 65 },
  { home: "HOU", away: "TCU", time: "2026-02-04T21:00:00Z", conference: "Big 12", homeScore: 84, awayScore: 71 },
  { home: "AUB", away: "MSST", time: "2026-02-04T23:00:00Z", conference: "SEC", homeScore: 89, awayScore: 76 },
  // Wednesday Feb 5
  { home: "UNC", away: "NCST", time: "2026-02-05T19:00:00Z", conference: "ACC", homeScore: 81, awayScore: 74 },
  { home: "MSU", away: "MICH", time: "2026-02-05T21:00:00Z", conference: "Big Ten", homeScore: 68, awayScore: 71 },
  // Thursday Feb 6
  { home: "MARQ", away: "NOVA", time: "2026-02-06T19:00:00Z", conference: "Big East", homeScore: 73, awayScore: 66 },
  { home: "TENN", away: "ARK", time: "2026-02-06T21:00:00Z", conference: "SEC", homeScore: 85, awayScore: 77 },

  // Upcoming games (no scores - today is Feb 8, 2026)
  // Saturday Feb 8
  { home: "DUKE", away: "UNC", time: "2026-02-08T18:00:00Z", conference: "ACC" },
  { home: "KU", away: "BAY", time: "2026-02-08T16:00:00Z", conference: "Big 12" },
  { home: "UK", away: "TENN", time: "2026-02-08T20:00:00Z", conference: "SEC" },
  { home: "PUR", away: "OSU", time: "2026-02-08T14:00:00Z", conference: "Big Ten" },
  { home: "GONZ", away: "SMC", time: "2026-02-08T22:00:00Z", conference: "WCC" },
  { home: "CONN", away: "MARQ", time: "2026-02-08T17:00:00Z", conference: "Big East" },
  { home: "HOU", away: "ISU", time: "2026-02-08T19:00:00Z", conference: "Big 12" },
  { home: "AUB", away: "ALA", time: "2026-02-08T21:00:00Z", conference: "SEC" },
  // Sunday Feb 9
  { home: "ARIZ", away: "COLO", time: "2026-02-09T18:00:00Z", conference: "Big 12" },
  { home: "UCLA", away: "ORE", time: "2026-02-09T20:00:00Z", conference: "Big Ten" },
  // Monday Feb 10
  { home: "MSU", away: "ILL", time: "2026-02-10T23:00:00Z", conference: "Big Ten" },
  // Tuesday Feb 11
  { home: "NOVA", away: "CREI", time: "2026-02-11T23:30:00Z", conference: "Big East" },
  { home: "FLA", away: "MISS", time: "2026-02-11T23:00:00Z", conference: "SEC" },
  // Wednesday Feb 12
  { home: "IND", away: "MINN", time: "2026-02-12T23:00:00Z", conference: "Big Ten" },
  { home: "TCU", away: "TTU", time: "2026-02-12T21:00:00Z", conference: "Big 12" },
];
