// FBS College Football Teams organized by conference (2024-25 season)

export const conferences = {
  SEC: [
    { name: "Alabama Crimson Tide", shortName: "Alabama", abbreviation: "ALA", primaryColor: "#9E1B32" },
    { name: "Arkansas Razorbacks", shortName: "Arkansas", abbreviation: "ARK", primaryColor: "#9D2235" },
    { name: "Auburn Tigers", shortName: "Auburn", abbreviation: "AUB", primaryColor: "#0C2340" },
    { name: "Florida Gators", shortName: "Florida", abbreviation: "FLA", primaryColor: "#0021A5" },
    { name: "Georgia Bulldogs", shortName: "Georgia", abbreviation: "UGA", primaryColor: "#BA0C2F" },
    { name: "Kentucky Wildcats", shortName: "Kentucky", abbreviation: "UK", primaryColor: "#0033A0" },
    { name: "LSU Tigers", shortName: "LSU", abbreviation: "LSU", primaryColor: "#461D7C" },
    { name: "Mississippi State Bulldogs", shortName: "Miss State", abbreviation: "MSST", primaryColor: "#660000" },
    { name: "Missouri Tigers", shortName: "Missouri", abbreviation: "MIZ", primaryColor: "#F1B82D" },
    { name: "Oklahoma Sooners", shortName: "Oklahoma", abbreviation: "OU", primaryColor: "#841617" },
    { name: "Ole Miss Rebels", shortName: "Ole Miss", abbreviation: "MISS", primaryColor: "#CE1126" },
    { name: "South Carolina Gamecocks", shortName: "South Carolina", abbreviation: "SC", primaryColor: "#73000A" },
    { name: "Tennessee Volunteers", shortName: "Tennessee", abbreviation: "TENN", primaryColor: "#FF8200" },
    { name: "Texas Longhorns", shortName: "Texas", abbreviation: "TEX", primaryColor: "#BF5700" },
    { name: "Texas A&M Aggies", shortName: "Texas A&M", abbreviation: "TAMU", primaryColor: "#500000" },
    { name: "Vanderbilt Commodores", shortName: "Vanderbilt", abbreviation: "VAN", primaryColor: "#866D4B" },
  ],
  "Big Ten": [
    { name: "Illinois Fighting Illini", shortName: "Illinois", abbreviation: "ILL", primaryColor: "#E84A27" },
    { name: "Indiana Hoosiers", shortName: "Indiana", abbreviation: "IND", primaryColor: "#990000" },
    { name: "Iowa Hawkeyes", shortName: "Iowa", abbreviation: "IOWA", primaryColor: "#FFCD00" },
    { name: "Maryland Terrapins", shortName: "Maryland", abbreviation: "MD", primaryColor: "#E03A3E" },
    { name: "Michigan Wolverines", shortName: "Michigan", abbreviation: "MICH", primaryColor: "#00274C" },
    { name: "Michigan State Spartans", shortName: "Michigan St", abbreviation: "MSU", primaryColor: "#18453B" },
    { name: "Minnesota Golden Gophers", shortName: "Minnesota", abbreviation: "MINN", primaryColor: "#7A0019" },
    { name: "Nebraska Cornhuskers", shortName: "Nebraska", abbreviation: "NEB", primaryColor: "#E41C38" },
    { name: "Northwestern Wildcats", shortName: "Northwestern", abbreviation: "NW", primaryColor: "#4E2A84" },
    { name: "Ohio State Buckeyes", shortName: "Ohio State", abbreviation: "OSU", primaryColor: "#BB0000" },
    { name: "Oregon Ducks", shortName: "Oregon", abbreviation: "ORE", primaryColor: "#154733" },
    { name: "Penn State Nittany Lions", shortName: "Penn State", abbreviation: "PSU", primaryColor: "#041E42" },
    { name: "Purdue Boilermakers", shortName: "Purdue", abbreviation: "PUR", primaryColor: "#CEB888" },
    { name: "Rutgers Scarlet Knights", shortName: "Rutgers", abbreviation: "RUT", primaryColor: "#CC0033" },
    { name: "UCLA Bruins", shortName: "UCLA", abbreviation: "UCLA", primaryColor: "#2D68C4" },
    { name: "USC Trojans", shortName: "USC", abbreviation: "USC", primaryColor: "#990000" },
    { name: "Washington Huskies", shortName: "Washington", abbreviation: "WASH", primaryColor: "#4B2E83" },
    { name: "Wisconsin Badgers", shortName: "Wisconsin", abbreviation: "WIS", primaryColor: "#C5050C" },
  ],
  "Big 12": [
    { name: "Arizona Wildcats", shortName: "Arizona", abbreviation: "ARIZ", primaryColor: "#CC0033" },
    { name: "Arizona State Sun Devils", shortName: "Arizona St", abbreviation: "ASU", primaryColor: "#8C1D40" },
    { name: "Baylor Bears", shortName: "Baylor", abbreviation: "BAY", primaryColor: "#154734" },
    { name: "BYU Cougars", shortName: "BYU", abbreviation: "BYU", primaryColor: "#002E5D" },
    { name: "Cincinnati Bearcats", shortName: "Cincinnati", abbreviation: "CIN", primaryColor: "#E00122" },
    { name: "Colorado Buffaloes", shortName: "Colorado", abbreviation: "COLO", primaryColor: "#CFB87C" },
    { name: "Houston Cougars", shortName: "Houston", abbreviation: "HOU", primaryColor: "#C8102E" },
    { name: "Iowa State Cyclones", shortName: "Iowa State", abbreviation: "ISU", primaryColor: "#C8102E" },
    { name: "Kansas Jayhawks", shortName: "Kansas", abbreviation: "KU", primaryColor: "#0051BA" },
    { name: "Kansas State Wildcats", shortName: "Kansas St", abbreviation: "KSU", primaryColor: "#512888" },
    { name: "Oklahoma State Cowboys", shortName: "Oklahoma St", abbreviation: "OKST", primaryColor: "#FF7300" },
    { name: "TCU Horned Frogs", shortName: "TCU", abbreviation: "TCU", primaryColor: "#4D1979" },
    { name: "Texas Tech Red Raiders", shortName: "Texas Tech", abbreviation: "TTU", primaryColor: "#CC0000" },
    { name: "UCF Knights", shortName: "UCF", abbreviation: "UCF", primaryColor: "#BA9B37" },
    { name: "Utah Utes", shortName: "Utah", abbreviation: "UTAH", primaryColor: "#CC0000" },
    { name: "West Virginia Mountaineers", shortName: "West Virginia", abbreviation: "WVU", primaryColor: "#002855" },
  ],
  ACC: [
    { name: "Boston College Eagles", shortName: "Boston College", abbreviation: "BC", primaryColor: "#98002E" },
    { name: "California Golden Bears", shortName: "California", abbreviation: "CAL", primaryColor: "#003262" },
    { name: "Clemson Tigers", shortName: "Clemson", abbreviation: "CLEM", primaryColor: "#F56600" },
    { name: "Duke Blue Devils", shortName: "Duke", abbreviation: "DUKE", primaryColor: "#003087" },
    { name: "Florida State Seminoles", shortName: "Florida St", abbreviation: "FSU", primaryColor: "#782F40" },
    { name: "Georgia Tech Yellow Jackets", shortName: "Georgia Tech", abbreviation: "GT", primaryColor: "#B3A369" },
    { name: "Louisville Cardinals", shortName: "Louisville", abbreviation: "LOU", primaryColor: "#AD0000" },
    { name: "Miami Hurricanes", shortName: "Miami", abbreviation: "MIA", primaryColor: "#F47321" },
    { name: "NC State Wolfpack", shortName: "NC State", abbreviation: "NCST", primaryColor: "#CC0000" },
    { name: "North Carolina Tar Heels", shortName: "North Carolina", abbreviation: "UNC", primaryColor: "#7BAFD4" },
    { name: "Pittsburgh Panthers", shortName: "Pittsburgh", abbreviation: "PITT", primaryColor: "#003594" },
    { name: "SMU Mustangs", shortName: "SMU", abbreviation: "SMU", primaryColor: "#0033A0" },
    { name: "Stanford Cardinal", shortName: "Stanford", abbreviation: "STAN", primaryColor: "#8C1515" },
    { name: "Syracuse Orange", shortName: "Syracuse", abbreviation: "SYR", primaryColor: "#F76900" },
    { name: "Virginia Cavaliers", shortName: "Virginia", abbreviation: "UVA", primaryColor: "#232D4B" },
    { name: "Virginia Tech Hokies", shortName: "Virginia Tech", abbreviation: "VT", primaryColor: "#630031" },
    { name: "Wake Forest Demon Deacons", shortName: "Wake Forest", abbreviation: "WAKE", primaryColor: "#9E7E38" },
  ],
  "American": [
    { name: "Army Black Knights", shortName: "Army", abbreviation: "ARMY", primaryColor: "#000000" },
    { name: "Charlotte 49ers", shortName: "Charlotte", abbreviation: "CHAR", primaryColor: "#046A38" },
    { name: "East Carolina Pirates", shortName: "East Carolina", abbreviation: "ECU", primaryColor: "#592A8A" },
    { name: "Florida Atlantic Owls", shortName: "FAU", abbreviation: "FAU", primaryColor: "#003366" },
    { name: "Memphis Tigers", shortName: "Memphis", abbreviation: "MEM", primaryColor: "#003087" },
    { name: "Navy Midshipmen", shortName: "Navy", abbreviation: "NAVY", primaryColor: "#00205B" },
    { name: "North Texas Mean Green", shortName: "North Texas", abbreviation: "UNT", primaryColor: "#00853E" },
    { name: "Rice Owls", shortName: "Rice", abbreviation: "RICE", primaryColor: "#00205B" },
    { name: "South Florida Bulls", shortName: "South Florida", abbreviation: "USF", primaryColor: "#006747" },
    { name: "Temple Owls", shortName: "Temple", abbreviation: "TEM", primaryColor: "#9D2235" },
    { name: "Tulane Green Wave", shortName: "Tulane", abbreviation: "TULN", primaryColor: "#006747" },
    { name: "Tulsa Golden Hurricane", shortName: "Tulsa", abbreviation: "TLSA", primaryColor: "#002D62" },
    { name: "UAB Blazers", shortName: "UAB", abbreviation: "UAB", primaryColor: "#1E6B52" },
    { name: "UTSA Roadrunners", shortName: "UTSA", abbreviation: "UTSA", primaryColor: "#0C2340" },
  ],
  "Mountain West": [
    { name: "Air Force Falcons", shortName: "Air Force", abbreviation: "AF", primaryColor: "#003087" },
    { name: "Boise State Broncos", shortName: "Boise State", abbreviation: "BSU", primaryColor: "#0033A0" },
    { name: "Colorado State Rams", shortName: "Colorado St", abbreviation: "CSU", primaryColor: "#1E4D2B" },
    { name: "Fresno State Bulldogs", shortName: "Fresno State", abbreviation: "FRES", primaryColor: "#DB0032" },
    { name: "Hawaii Rainbow Warriors", shortName: "Hawaii", abbreviation: "HAW", primaryColor: "#024731" },
    { name: "Nevada Wolf Pack", shortName: "Nevada", abbreviation: "NEV", primaryColor: "#003366" },
    { name: "New Mexico Lobos", shortName: "New Mexico", abbreviation: "UNM", primaryColor: "#BA0C2F" },
    { name: "San Diego State Aztecs", shortName: "San Diego St", abbreviation: "SDSU", primaryColor: "#A6192E" },
    { name: "San Jose State Spartans", shortName: "San Jose St", abbreviation: "SJSU", primaryColor: "#0055A2" },
    { name: "UNLV Rebels", shortName: "UNLV", abbreviation: "UNLV", primaryColor: "#CF0A2C" },
    { name: "Utah State Aggies", shortName: "Utah State", abbreviation: "USU", primaryColor: "#0F2439" },
    { name: "Wyoming Cowboys", shortName: "Wyoming", abbreviation: "WYO", primaryColor: "#492F24" },
  ],
  "Sun Belt": [
    { name: "Appalachian State Mountaineers", shortName: "App State", abbreviation: "APP", primaryColor: "#FFCC00" },
    { name: "Arkansas State Red Wolves", shortName: "Arkansas St", abbreviation: "ARST", primaryColor: "#CC092F" },
    { name: "Coastal Carolina Chanticleers", shortName: "Coastal", abbreviation: "CCU", primaryColor: "#006F71" },
    { name: "Georgia Southern Eagles", shortName: "Ga Southern", abbreviation: "GASO", primaryColor: "#011E41" },
    { name: "Georgia State Panthers", shortName: "Georgia St", abbreviation: "GAST", primaryColor: "#0039A6" },
    { name: "James Madison Dukes", shortName: "James Madison", abbreviation: "JMU", primaryColor: "#450084" },
    { name: "Louisiana Ragin Cajuns", shortName: "Louisiana", abbreviation: "ULL", primaryColor: "#CE181E" },
    { name: "Louisiana-Monroe Warhawks", shortName: "ULM", abbreviation: "ULM", primaryColor: "#840029" },
    { name: "Marshall Thundering Herd", shortName: "Marshall", abbreviation: "MRSH", primaryColor: "#00B140" },
    { name: "Old Dominion Monarchs", shortName: "Old Dominion", abbreviation: "ODU", primaryColor: "#003057" },
    { name: "South Alabama Jaguars", shortName: "South Alabama", abbreviation: "USA", primaryColor: "#00205B" },
    { name: "Southern Miss Golden Eagles", shortName: "Southern Miss", abbreviation: "USM", primaryColor: "#FFAB00" },
    { name: "Texas State Bobcats", shortName: "Texas State", abbreviation: "TXST", primaryColor: "#501214" },
    { name: "Troy Trojans", shortName: "Troy", abbreviation: "TROY", primaryColor: "#8A2432" },
  ],
  "MAC": [
    { name: "Akron Zips", shortName: "Akron", abbreviation: "AKR", primaryColor: "#041E42" },
    { name: "Ball State Cardinals", shortName: "Ball State", abbreviation: "BALL", primaryColor: "#BA0C2F" },
    { name: "Bowling Green Falcons", shortName: "Bowling Green", abbreviation: "BGSU", primaryColor: "#FE5000" },
    { name: "Buffalo Bulls", shortName: "Buffalo", abbreviation: "BUFF", primaryColor: "#005BBB" },
    { name: "Central Michigan Chippewas", shortName: "C Michigan", abbreviation: "CMU", primaryColor: "#6A0032" },
    { name: "Eastern Michigan Eagles", shortName: "E Michigan", abbreviation: "EMU", primaryColor: "#006633" },
    { name: "Kent State Golden Flashes", shortName: "Kent State", abbreviation: "KENT", primaryColor: "#002664" },
    { name: "Miami (OH) RedHawks", shortName: "Miami OH", abbreviation: "M-OH", primaryColor: "#B61E2E" },
    { name: "Northern Illinois Huskies", shortName: "N Illinois", abbreviation: "NIU", primaryColor: "#BA0C2F" },
    { name: "Ohio Bobcats", shortName: "Ohio", abbreviation: "OHIO", primaryColor: "#00694E" },
    { name: "Toledo Rockets", shortName: "Toledo", abbreviation: "TOL", primaryColor: "#15397F" },
    { name: "Western Michigan Broncos", shortName: "W Michigan", abbreviation: "WMU", primaryColor: "#6C4023" },
  ],
  "C-USA": [
    { name: "FIU Panthers", shortName: "FIU", abbreviation: "FIU", primaryColor: "#002D62" },
    { name: "Jacksonville State Gamecocks", shortName: "Jax State", abbreviation: "JAX", primaryColor: "#CC0000" },
    { name: "Kennesaw State Owls", shortName: "Kennesaw St", abbreviation: "KENN", primaryColor: "#FDBB30" },
    { name: "Liberty Flames", shortName: "Liberty", abbreviation: "LIB", primaryColor: "#002D62" },
    { name: "Louisiana Tech Bulldogs", shortName: "La Tech", abbreviation: "LT", primaryColor: "#002F8B" },
    { name: "Middle Tennessee Blue Raiders", shortName: "MTSU", abbreviation: "MTSU", primaryColor: "#0066CC" },
    { name: "New Mexico State Aggies", shortName: "NM State", abbreviation: "NMSU", primaryColor: "#8B0000" },
    { name: "Sam Houston Bearkats", shortName: "Sam Houston", abbreviation: "SHSU", primaryColor: "#F68B1F" },
    { name: "UTEP Miners", shortName: "UTEP", abbreviation: "UTEP", primaryColor: "#FF8200" },
    { name: "Western Kentucky Hilltoppers", shortName: "WKU", abbreviation: "WKU", primaryColor: "#B01E24" },
  ],
  Independents: [
    { name: "Notre Dame Fighting Irish", shortName: "Notre Dame", abbreviation: "ND", primaryColor: "#0C2340" },
    { name: "UConn Huskies", shortName: "UConn", abbreviation: "CONN", primaryColor: "#000E2F" },
    { name: "UMass Minutemen", shortName: "UMass", abbreviation: "MASS", primaryColor: "#881C1C" },
  ],
};
